config/routes.rb
RubyBlog::Application.routes.draw do
  devise_for :admins
  root :to => 'users#index'
  scope "/" do
    get "/post/:id" => "users#show", :as => :show_post_comments
    post "/post/:id" => "users#create", :as => :create_comment
  end

  get "/administration" => "administration/comments#index"
  get "/search" => "search#index"

  get "/categories/:name" => "tags#index", :as => :tags

  namespace :administration do
    resources :admins
    resources :posts do
      collection do
        get :preview
      end
      resources :comments, :only => [:new, :create]
    end
    resources :comments, :except => [:new, :create]
    resources :tags
    resources :sitemap, :only => [:index, :create]
  end
  delete "/administration/tags/destroy/:id" => "administration/tags#destroy!", :as => :administration_destroy_tag
  get "/administration/search_tag" => "administration/tags#search_tag", :as => :administration_search_tag
  get "/administration/admins/disable/:id" => "administration/admins#disable", :as => :disable_administration_admin
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :posts
  validates :name, :presence => true, :uniqueness => true

  before_save :normalize_tag

  private
  def normalize_tag
    self.name.strip!
    self.name.gsub!(/[^\w|^\s]/, "_")
  end
end

app/controllers/administration/admins_controller.rb
class Administration::AdminsController < Administration::MainController

  before_filter :find_admin, :only => [:show, :edit, :update, :destroy]

  def index
    @search = Admin.search(admin_params || {"meta_sort" => "id.asc"})
    @admins = @search.result(distinct: true).paginate(:per_page => 10, :page => params[:page])
  end

  def show
  end

  def new
    @admin = Admin.new
  end

  def edit
  end

  def update
    if @admin.update_attributes(admin_params)
      flash[:notice] = "Account updated successfully"
      redirect_to administration_admin_path(@admin)
    else
      flash[:error] = @admin.errors.to_a
      render :action => :edit
    end
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      flash[:notice] = "Account created successfully"
      redirect_to administration_admin_path(@admin)
    else
      flash[:error] = @admin.errors.to_a
      render :action => :new
    end
  end

  def destroy
    if current_admin.superadmin?
      if @admin.locked_at?
        @admin.unlock_access!
        flash[:notice] = "#{@admin.username} is enable"
      else
        @admin.lock_access!
        flash[:notice] = "#{@admin.username} is disable"
      end
    else
      flash[:error]="You can't block"
    end
    redirect_to administration_admins_path
  end

  private

  def admin_params
    params[:admin].present? &&
      params.require(:admin).permit(:email, :password, :password_confirmation, :remember_me, :username, :nick, :avatar, :subscribe, :search, :page )
  end

  def find_admin
    @admin=Admin.find_by_id(params[:id])
    unless @admin
      flash[:error]="Admin with id #{params[:id]} does not exist!"
      redirect_to administration_admins_path
    end
  end

end

app/controllers/administration/comments_controller.rb
class Administration::CommentsController < Administration::MainController

  before_filter :find_comment, :except => [:index, :new, :create]
  before_filter :build_comment, :only => [:new, :create]
  def index
    @search = Comment.includes(:post).search(comment_params || {"meta_sort" => "id.asc"})
    @comments = @search.result(distinct: true).paginate(:per_page => 50, :page => params[:page])
  end

  def edit
  end

  def new
  end

  def update
    @comment.current_admin = current_admin
    if @comment.update_attributes(params.require(:comment).permit(:author, :content))
      flash[:notice] = "Comment updated successfully"
      redirect_to administration_post_path(@comment.post)
    else
      flash[:error] = "Error raised while comment's update'"
      render :action => :edit
    end
  end

  def create
    if @comment.save
      flash[:notice] = "Comment created successfully"
      redirect_to administration_post_path(@post)
    else
      flash[:error] = "All fields should not be empty"
      render :action => :new
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = "Comment deleted successfully"
    redirect_to administration_post_path(@comment.post)
  end

  private

  def comment_params
    params.permit(:post_id, :content, :author, :search, :page, :comment)
  end

  def build_comment
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment] ? params.require(:comment).permit(:author, :content) : {})
    @comment.current_admin=current_admin.id
  end

  def find_comment
    @comment = Comment.includes(:post).find(params[:id])
  end

end

app/controllers/administration/main_controller.rb
class Administration::MainController < ActionController::Base
  before_filter :authenticate_admin!
  layout 'admin'
end

app/controllers/administration/posts_controller.rb
class Administration::PostsController < Administration::MainController

  before_filter :find_post, :only => [:update, :destroy]

  def index
    @search = Post.includes(:admin).search(posts_params || {"meta_sort" => "id.asc"})
    @posts = @search.result(distinct: true).paginate(:per_page => 20, :page => params[:page])
  end

  def edit
    @post = Post.includes(:tags).find(params[:id])
  end

  def update
    if @post.update_attributes(posts_params[:post])
      flash[:notice] = "Post successfully updated"
      redirect_to administration_post_path
    else
      flash[:error] = @post.errors.full_messages
      render :action => :edit
    end
  end

  def show
    @post = Post.includes([:comments, :tags]).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_admin.posts.build(posts_params[:post])
    if @post.save
      flash[:notice] = "Post successfully saved"
      redirect_to administration_post_path(@post)
    else
      flash[:error] = @post.errors.full_messages
      render :action => :new
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Destroyed successfully"    
    redirect_to administration_posts_path
  end

  def preview
    @tags = []
    @post = Post.where(:id => params[:id]).first || Post.new
    render :layout => 'application'
  end

  private

  def posts_params
    params.permit(post: [:subject, :message, :status, :truncate_character])
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/administration/sitemap_controller.rb
class Administration::SitemapController < Administration::MainController
  def index
    @files = Dir["#{Rails.public_path}/sitemaps/*.xml.gz"].map {|x| {:name => File.basename(x), :date => File.ctime(x)}}
  end

  def create
    %x[rake 'sitemap:refresh']
    redirect_to administration_sitemap_index_path, :notice => 'Successfully generated...'
  end
end

app/controllers/administration/tags_controller.rb
class Administration::TagsController < Administration::MainController

    before_filter :find_post, :only => [:create, :destroy]
    before_filter :find_tag, :only => [:edit, :update, :destroy!, :destroy]

  def index
    @search = Tag.search(params[:q] || {"meta_sort" => "id.asc"})
    @tags = @search.result(distinct: true).paginate(:per_page => 20, :page => params[:page])
  end

  def create
    tag = Tag.find_or_create_by(:name => tag_params[:name])
    unless @post.nil? or @post.tags.exists?(tag)
      @post.tags << tag
      result = {:tag => render_to_string(:partial => 'tag', :locals =>{:tag => tag, :post => @post})}
    end
    result ||= {:error => "Association between tag_id #{tag.id} and post_id #{params[:post_id]} already exist or post not found"}
    render :json => result
  end

  def update
    if @tag.update_attributes(tag_params)
      flash[:notice] = "Updated successfully"
      redirect_to administration_tags_path
    else
      flash[:error] = @tag.errors.to_a
      render :action => :edit
    end
  end

  def search_tag
    tag = Tag.where("LOWER(name) LIKE (?)", "%#{params[:q].to_s.downcase}%")
    render :text => tag.map(&:name).uniq.join("\n")
  end

  def destroy
    if @tag and @post and @post.tags.delete(@tag)
      render :text => "ok"
    else
      render :text => "Error while deleting association between tag_id #{params[:id]} and post_id #{params[:post_id]}"
    end
  end

  def destroy!
      @tag.destroy
      flash[:notice] = "Tag #{@tag.name} has been successfully deleted"
      redirect_to administration_tags_path
  end

  private

  def tag_params
    params[:tag].permit(:name, :post_id, :q, :search, :page)
  end

  def find_post
    @post = Post.find_by_id(params[:post_id])
  end

  def find_tag
    unless @tag = Tag.find_by(:id => params[:id])
      flash[:error] = "Tag with id #{params[:id]} not found"
      redirect_to administration_tags_path unless request.xhr?
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @posts = Post.joins(:tags, :admin).where('tags.name = ?', tag_params[:name]).
        enabled.order("posts.created_at DESC").preload(:tags, :admin).
        paginate(:per_page => 5, :page => params[:page])
    render :template => "users/index"
  end

  private

  def tag_params
    params.permit(:name)
  end

end

app/helpers/administration/main_helper.rb
module Administration::MainHelper
  def has_active_class?(href)
    current_page?(href) ? {:class => "active"} : []
  end
end

app/views/administration/tags/_sidebar.html.haml
.block.notice
  %h3 Search
  .tag_search
    = form_for :comment, :url => administration_tags_path, :html => {:method => :get} do |f|
      %p
        %h4 Tag:
        = f.text_field :name_cont

      %h3 Search params:
      .search_attr
        %p
          = f.check_box :status_true
          = f.label :status, "Hidden "
        %p
          = f.check_box :status_false
          = f.label :status, "Unhidden "

      %p
        = f.submit "Search"
        = link_to "Reset",administration_tags_path

app/views/administration/tags/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "#{t("web-app-theme.list", :default => "List")}", administration_tags_path
      %li.active= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_administration_tag_path
  .content
    %h2.title
      = t("web-app-theme.edit", :default => "Edit")
      = "Tag #{@tag.name}"
    .inner
      = form_for @tag, :url => administration_tag_path(current_admin), :html => { :class => :form } do |f|
        .group
          =f.label :name
          =f.text_field :name
        .group
          %p
            =f.label "Hide this tag "
            =f.check_box :status
        .group.navform.wat-cf
          %button.button{:type => "submit"}
            = image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}")
            = t("web-app-theme.save", :default => "Save")

app/views/administration/tags/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "List", administration_tags_path
  .content
    %h2.title
      All Tags
    .inner
      %table.table
        %tr
          %th= sort_link @search, :id, "ID"
          %th= sort_link @search, :name, "Name"
          %th.last
        - @tags.each do |tag|
          %tr{:class => cycle("odd", "even")}
            %td
              = tag.id
            %td
              = tag.name
            %td.last
              = link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_administration_tag_path(tag)
              |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", administration_destroy_tag_path(tag), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
        = will_paginate @tags
- content_for :sidebar, render(:partial => 'sidebar')