config/routes.rb
RubyBlog::Application.routes.draw do
  devise_for :admins
  root :to => 'users#index'
  scope "/" do
    get "/post/:id" => "users#show", :as => :show_post_comments
    post "/post/:id" => "users#create", :as => :create_comment
  end

  get "/administration" => "administration/comments#index"
  get "/search" => "search#index"

  get "/categories/:name" => "tags#index", :as => :tags

  namespace :administration do
    resources :admins
    resources :posts do
      collection do
        get :preview
      end
      resources :comments, :only => [:new, :create]
    end
    resources :comments, :except => [:new, :create]
    resources :tags
    resources :sitemap, :only => [:index, :create]
  end
  delete "/administration/tags/destroy/:id" => "administration/tags#destroy!", :as => :administration_destroy_tag
  get "/administration/search_tag" => "administration/tags#search_tag", :as => :administration_search_tag
  get "/administration/admins/disable/:id" => "administration/admins#disable", :as => :disable_administration_admin
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :admin
  has_many :comments, :dependent => :destroy
  has_and_belongs_to_many :tags

  validates :admin_id, :subject, :message, :presence => true
  validates :truncate_character, :numericality => {:only_integer => true, :grater_than => 0}

  before_save :update_post_message

  def update_post_message
    self.message = Nokogiri::HTML.parse(self.message).search("body").inner_html
  end

  scope :enabled, -> { where(" \"posts\".status = 'false' ")}

  def to_param
    "#{id}-#{RusAlpha.translate(subject.to_s).parameterize}"
  end

end

app/controllers/administration/admins_controller.rb
class Administration::AdminsController < Administration::MainController

  before_filter :find_admin, :only => [:show, :edit, :update, :destroy]

  def index
    @search = Admin.search(admin_params || {"meta_sort" => "id.asc"})
    @admins = @search.result(distinct: true).paginate(:per_page => 10, :page => params[:page])
  end

  def show
  end

  def new
    @admin = Admin.new
  end

  def edit
  end

  def update
    if @admin.update_attributes(admin_params)
      flash[:notice] = "Account updated successfully"
      redirect_to administration_admin_path(@admin)
    else
      flash[:error] = @admin.errors.to_a
      render :action => :edit
    end
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      flash[:notice] = "Account created successfully"
      redirect_to administration_admin_path(@admin)
    else
      flash[:error] = @admin.errors.to_a
      render :action => :new
    end
  end

  def destroy
    if current_admin.superadmin?
      if @admin.locked_at?
        @admin.unlock_access!
        flash[:notice] = "#{@admin.username} is enable"
      else
        @admin.lock_access!
        flash[:notice] = "#{@admin.username} is disable"
      end
    else
      flash[:error]="You can't block"
    end
    redirect_to administration_admins_path
  end

  private

  def admin_params
    params[:admin].present? &&
      params.require(:admin).permit(:email, :password, :password_confirmation, :remember_me, :username, :nick, :avatar, :subscribe, :search, :page )
  end

  def find_admin
    @admin=Admin.find_by_id(params[:id])
    unless @admin
      flash[:error]="Admin with id #{params[:id]} does not exist!"
      redirect_to administration_admins_path
    end
  end

end

app/controllers/administration/comments_controller.rb
class Administration::CommentsController < Administration::MainController

  before_filter :find_comment, :except => [:index, :new, :create]
  before_filter :build_comment, :only => [:new, :create]
  def index
    @search = Comment.includes(:post).search(comment_params || {"meta_sort" => "id.asc"})
    @comments = @search.result(distinct: true).paginate(:per_page => 50, :page => params[:page])
  end

  def edit
  end

  def new
  end

  def update
    @comment.current_admin = current_admin
    if @comment.update_attributes(params.require(:comment).permit(:author, :content))
      flash[:notice] = "Comment updated successfully"
      redirect_to administration_post_path(@comment.post)
    else
      flash[:error] = "Error raised while comment's update'"
      render :action => :edit
    end
  end

  def create
    if @comment.save
      flash[:notice] = "Comment created successfully"
      redirect_to administration_post_path(@post)
    else
      flash[:error] = "All fields should not be empty"
      render :action => :new
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = "Comment deleted successfully"
    redirect_to administration_post_path(@comment.post)
  end

  private

  def comment_params
    params.permit(:post_id, :content, :author, :search, :page, :comment)
  end

  def build_comment
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment] ? params.require(:comment).permit(:author, :content) : {})
    @comment.current_admin=current_admin.id
  end

  def find_comment
    @comment = Comment.includes(:post).find(params[:id])
  end

end

app/controllers/administration/main_controller.rb
class Administration::MainController < ActionController::Base
  before_filter :authenticate_admin!
  layout 'admin'
end

app/controllers/administration/posts_controller.rb
class Administration::PostsController < Administration::MainController

  before_filter :find_post, :only => [:update, :destroy]

  def index
    @search = Post.includes(:admin).search(posts_params || {"meta_sort" => "id.asc"})
    @posts = @search.result(distinct: true).paginate(:per_page => 20, :page => params[:page])
  end

  def edit
    @post = Post.includes(:tags).find(params[:id])
  end

  def update
    if @post.update_attributes(posts_params[:post])
      flash[:notice] = "Post successfully updated"
      redirect_to administration_post_path
    else
      flash[:error] = @post.errors.full_messages
      render :action => :edit
    end
  end

  def show
    @post = Post.includes([:comments, :tags]).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_admin.posts.build(posts_params[:post])
    if @post.save
      flash[:notice] = "Post successfully saved"
      redirect_to administration_post_path(@post)
    else
      flash[:error] = @post.errors.full_messages
      render :action => :new
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Destroyed successfully"    
    redirect_to administration_posts_path
  end

  def preview
    @tags = []
    @post = Post.where(:id => params[:id]).first || Post.new
    render :layout => 'application'
  end

  private

  def posts_params
    params.permit(post: [:subject, :message, :status, :truncate_character])
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/administration/sitemap_controller.rb
class Administration::SitemapController < Administration::MainController
  def index
    @files = Dir["#{Rails.public_path}/sitemaps/*.xml.gz"].map {|x| {:name => File.basename(x), :date => File.ctime(x)}}
  end

  def create
    %x[rake 'sitemap:refresh']
    redirect_to administration_sitemap_index_path, :notice => 'Successfully generated...'
  end
end

app/controllers/administration/tags_controller.rb
class Administration::TagsController < Administration::MainController

    before_filter :find_post, :only => [:create, :destroy]
    before_filter :find_tag, :only => [:edit, :update, :destroy!, :destroy]

  def index
    @search = Tag.search(params[:q] || {"meta_sort" => "id.asc"})
    @tags = @search.result(distinct: true).paginate(:per_page => 20, :page => params[:page])
  end

  def create
    tag = Tag.find_or_create_by(:name => tag_params[:name])
    unless @post.nil? or @post.tags.exists?(tag)
      @post.tags << tag
      result = {:tag => render_to_string(:partial => 'tag', :locals =>{:tag => tag, :post => @post})}
    end
    result ||= {:error => "Association between tag_id #{tag.id} and post_id #{params[:post_id]} already exist or post not found"}
    render :json => result
  end

  def update
    if @tag.update_attributes(tag_params)
      flash[:notice] = "Updated successfully"
      redirect_to administration_tags_path
    else
      flash[:error] = @tag.errors.to_a
      render :action => :edit
    end
  end

  def search_tag
    tag = Tag.where("LOWER(name) LIKE (?)", "%#{params[:q].to_s.downcase}%")
    render :text => tag.map(&:name).uniq.join("\n")
  end

  def destroy
    if @tag and @post and @post.tags.delete(@tag)
      render :text => "ok"
    else
      render :text => "Error while deleting association between tag_id #{params[:id]} and post_id #{params[:post_id]}"
    end
  end

  def destroy!
      @tag.destroy
      flash[:notice] = "Tag #{@tag.name} has been successfully deleted"
      redirect_to administration_tags_path
  end

  private

  def tag_params
    params[:tag].permit(:name, :post_id, :q, :search, :page)
  end

  def find_post
    @post = Post.find_by_id(params[:post_id])
  end

  def find_tag
    unless @tag = Tag.find_by(:id => params[:id])
      flash[:error] = "Tag with id #{params[:id]} not found"
      redirect_to administration_tags_path unless request.xhr?
    end
  end

end

app/helpers/administration/main_helper.rb
module Administration::MainHelper
  def has_active_class?(href)
    current_page?(href) ? {:class => "active"} : []
  end
end

app/views/administration/posts/_form.html.haml
.group
  = f.label "Subject:"
  = f.text_field :subject
  = f.label "Disable this post"
  = f.check_box :status
  %p
    = f.label "Number of characters to show:"
    = f.text_field :truncate_character
.group
  = f.label "Message:"
  = f.cktext_area :message
.group.navform.wat-cf
  = f.submit "Save"
  = link_to "Cancel", administration_posts_path
%br>
%iframe{:src => preview_administration_posts_path(:id => @post.id.to_s), :id => "post-iframe", :width => "100%", :height => "480"}

app/views/administration/posts/_search_sidebar.html.haml
.block.notice
  %h3 Search
  .post_search
    = form_for :post, :url => administration_posts_path, :html => {:method => :get} do |f|
      .search_attr
        %p
          = f.label :created_at, "Begin Date "
          = f.date_select :created_at, :default=>5.years.ago
        %p
          = f.label :created_at, "End Date "
          = f.date_select :created_at
        %p
          = f.check_box :status
          = f.label :status, "Disable "
      %p
        = f.submit "Search"
        = link_to "Reset",administration_posts_path

app/views/administration/posts/_sidebar.html.haml
.block.notice
  .content
.block
  %h3 Manage tags
  %ul.navigation
    - post.tags.each do |tag|
      = render :partial => 'tag', :locals => {:tag => tag, :post => post}
  .new-tag
    = form_for :tags, :html => {:id => "tag-form"} do |f|
      = hidden_field_tag :post_id, post.id
      = f.text_field :name
      = f.submit "Add Tag"

app/views/administration/posts/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "List", administration_posts_path
      %li= link_to "New", new_administration_post_path
      %li.active= link_to "Edit", edit_administration_post_path(@post)
  .content
    %h2.title
      = @post.subject
    .inner
      = form_for @post, :url => administration_post_path(@post) do |f|
        = f.label "Time Created:"
        = f.datetime_select :created_at
        = render :partial => 'form', :locals => {:f => f}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar', :locals => {:post => @post})

app/views/administration/posts/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "List", "#"
      %li= link_to "New", new_administration_post_path
  .content
    %h2.title
      All Posts
    .inner
      %table.table
        %tr
          %th= sort_link @search, :subject, "Subject"
          %th= sort_link @search, :created_at, "Created at"
          %th= sort_link @search, :nick, t("activerecord.attributes.administration_admin.nick", :default => t("activerecord.labels.nick", :default => "Nick"))
          %th.last &nbsp;
        - @posts.each do |post|
          %tr{:class => cycle("odd", "even")}
            %td
              = post.subject
            %td
              = l(post.created_at, :format => :long)
            %td
              = link_to post.admin.nick, administration_admin_path(post.admin.nick)
            %td.last
              = link_to "#{t("web-app-theme.show", :default => "Show")}", administration_post_path(post)
              |
              \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_administration_post_path(post)}
              |
              \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", administration_post_path(post), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      .actions-bar.wat-cf
        .actions
      = will_paginate @posts
- content_for :sidebar, render(:partial => 'search_sidebar')

app/views/administration/posts/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "List", administration_posts_path
      %li.active= link_to "New", "#"
  .content
    %h2.title
      New Post
    .inner
      = form_for @post, :url => administration_posts_path do |f|
        = render :partial => 'form', :locals => {:f => f}
      .actions-bar.wat-cf
        .actions

app/views/administration/posts/preview.html.haml
.content
  .center
    .item
      %h2
        = @post.subject
      .by
        = "Posted by #{current_admin.nick}@#{Time.now}"
      #post-body
        = raw @post.message
      .clear

  .clear

:javascript
  $(document).ready(function(){
    $('.header').remove();
    $('.right').remove();
  });

app/views/administration/posts/show.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "List", administration_posts_path
      %li= link_to "New", new_administration_post_path
      %li.active= link_to "Show", administration_post_path(@post)
  .content
    %h2.title
      = @post.subject
    .inner
      .table
        .group
          Содержание поста:
          %div{:style => "border: 1px dashed #576C82;"}
            =raw truncate_html(@post)
          %p
            Количество символов на главное странице:
            =@post.truncate_character
          %p
            Created at:
            = l(@post.created_at,:format => :long)
          %p
            Author:
            = @post.admin.nick
          %p
            Статус:
            = @post.status ? "Disabled" : "Enabled"          
        = link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_administration_post_path, :class => "button"
        %br>

    .inner
      = link_to "New comment", new_administration_post_comment_path(@post)
      %table.table
        %tr
          %th.first Comments
          %th.last &nbsp;
        - @post.comments.each do |comment|
          %tr{:class => cycle("odd", "even")}
            %td= comment.content
            %td.last.show-comments
              %p
                %strong
                  ID:
                = comment.id
              %p
                %strong
                  Author:
                = comment.author
              %p
                %strong
                  Created at:
                = l(comment.created_at,:format => :long)
              %p
                %strong
                  Updated at:
                = l(comment.updated_at,:format => :long)
              %p
                \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_administration_comment_path(comment)}
                |
                \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", administration_comment_path(comment), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}
      = link_to "New comment", new_administration_post_comment_path(@post)
- content_for :sidebar, render(:partial => 'sidebar', :locals => {:post => @post})