config/routes.rb
RubyBlog::Application.routes.draw do
  devise_for :admins
  root :to => 'users#index'
  scope "/" do
    get "/post/:id" => "users#show", :as => :show_post_comments
    post "/post/:id" => "users#create", :as => :create_comment
  end

  get "/administration" => "administration/comments#index"
  get "/search" => "search#index"

  get "/categories/:name" => "tags#index", :as => :tags

  namespace :administration do
    resources :admins
    resources :posts do
      collection do
        get :preview
      end
      resources :comments, :only => [:new, :create]
    end
    resources :comments, :except => [:new, :create]
    resources :tags
    resources :sitemap, :only => [:index, :create]
  end
  delete "/administration/tags/destroy/:id" => "administration/tags#destroy!", :as => :administration_destroy_tag
  get "/administration/search_tag" => "administration/tags#search_tag", :as => :administration_search_tag
  get "/administration/admins/disable/:id" => "administration/admins#disable", :as => :disable_administration_admin
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  apply_simple_captcha

  attr_accessor :current_admin
  belongs_to :post

  after_create :notify_admin

  validates :content, :post_id, :author, :presence => true
  validates :content, :length => {:minimum => 1, :maximum => 10000}
  validates :author, :length => {:minimum => 3, :maximum => 20}
  validate :check_author

  protected

  def notify_admin
    AdminMailer.comment_notifier(id).deliver
  rescue
    nil
  end

  def check_author
    nick = Admin.select(:nick).where(:nick => self.author.strip.downcase).exists?
    errors.add(:author, "Nick #{self.author} has already been taken by admin") if nick && !self.current_admin
  end

end

app/controllers/administration/admins_controller.rb
class Administration::AdminsController < Administration::MainController

  before_filter :find_admin, :only => [:show, :edit, :update, :destroy]

  def index
    @search = Admin.search(admin_params || {"meta_sort" => "id.asc"})
    @admins = @search.result(distinct: true).paginate(:per_page => 10, :page => params[:page])
  end

  def show
  end

  def new
    @admin = Admin.new
  end

  def edit
  end

  def update
    if @admin.update_attributes(admin_params)
      flash[:notice] = "Account updated successfully"
      redirect_to administration_admin_path(@admin)
    else
      flash[:error] = @admin.errors.to_a
      render :action => :edit
    end
  end

  def create
    @admin = Admin.new(admin_params)
    if @admin.save
      flash[:notice] = "Account created successfully"
      redirect_to administration_admin_path(@admin)
    else
      flash[:error] = @admin.errors.to_a
      render :action => :new
    end
  end

  def destroy
    if current_admin.superadmin?
      if @admin.locked_at?
        @admin.unlock_access!
        flash[:notice] = "#{@admin.username} is enable"
      else
        @admin.lock_access!
        flash[:notice] = "#{@admin.username} is disable"
      end
    else
      flash[:error]="You can't block"
    end
    redirect_to administration_admins_path
  end

  private

  def admin_params
    params[:admin].present? &&
      params.require(:admin).permit(:email, :password, :password_confirmation, :remember_me, :username, :nick, :avatar, :subscribe, :search, :page )
  end

  def find_admin
    @admin=Admin.find_by_id(params[:id])
    unless @admin
      flash[:error]="Admin with id #{params[:id]} does not exist!"
      redirect_to administration_admins_path
    end
  end

end

app/controllers/administration/comments_controller.rb
class Administration::CommentsController < Administration::MainController

  before_filter :find_comment, :except => [:index, :new, :create]
  before_filter :build_comment, :only => [:new, :create]
  def index
    @search = Comment.includes(:post).search(comment_params || {"meta_sort" => "id.asc"})
    @comments = @search.result(distinct: true).paginate(:per_page => 50, :page => params[:page])
  end

  def edit
  end

  def new
  end

  def update
    @comment.current_admin = current_admin
    if @comment.update_attributes(params.require(:comment).permit(:author, :content))
      flash[:notice] = "Comment updated successfully"
      redirect_to administration_post_path(@comment.post)
    else
      flash[:error] = "Error raised while comment's update'"
      render :action => :edit
    end
  end

  def create
    if @comment.save
      flash[:notice] = "Comment created successfully"
      redirect_to administration_post_path(@post)
    else
      flash[:error] = "All fields should not be empty"
      render :action => :new
    end
  end

  def destroy
    @comment.destroy
    flash[:notice] = "Comment deleted successfully"
    redirect_to administration_post_path(@comment.post)
  end

  private

  def comment_params
    params.permit(:post_id, :content, :author, :search, :page, :comment)
  end

  def build_comment
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params[:comment] ? params.require(:comment).permit(:author, :content) : {})
    @comment.current_admin=current_admin.id
  end

  def find_comment
    @comment = Comment.includes(:post).find(params[:id])
  end

end

app/controllers/administration/main_controller.rb
class Administration::MainController < ActionController::Base
  before_filter :authenticate_admin!
  layout 'admin'
end

app/controllers/administration/posts_controller.rb
class Administration::PostsController < Administration::MainController

  before_filter :find_post, :only => [:update, :destroy]

  def index
    @search = Post.includes(:admin).search(posts_params || {"meta_sort" => "id.asc"})
    @posts = @search.result(distinct: true).paginate(:per_page => 20, :page => params[:page])
  end

  def edit
    @post = Post.includes(:tags).find(params[:id])
  end

  def update
    if @post.update_attributes(posts_params[:post])
      flash[:notice] = "Post successfully updated"
      redirect_to administration_post_path
    else
      flash[:error] = @post.errors.full_messages
      render :action => :edit
    end
  end

  def show
    @post = Post.includes([:comments, :tags]).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_admin.posts.build(posts_params[:post])
    if @post.save
      flash[:notice] = "Post successfully saved"
      redirect_to administration_post_path(@post)
    else
      flash[:error] = @post.errors.full_messages
      render :action => :new
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Destroyed successfully"    
    redirect_to administration_posts_path
  end

  def preview
    @tags = []
    @post = Post.where(:id => params[:id]).first || Post.new
    render :layout => 'application'
  end

  private

  def posts_params
    params.permit(post: [:subject, :message, :status, :truncate_character])
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/administration/sitemap_controller.rb
class Administration::SitemapController < Administration::MainController
  def index
    @files = Dir["#{Rails.public_path}/sitemaps/*.xml.gz"].map {|x| {:name => File.basename(x), :date => File.ctime(x)}}
  end

  def create
    %x[rake 'sitemap:refresh']
    redirect_to administration_sitemap_index_path, :notice => 'Successfully generated...'
  end
end

app/controllers/administration/tags_controller.rb
class Administration::TagsController < Administration::MainController

    before_filter :find_post, :only => [:create, :destroy]
    before_filter :find_tag, :only => [:edit, :update, :destroy!, :destroy]

  def index
    @search = Tag.search(params[:q] || {"meta_sort" => "id.asc"})
    @tags = @search.result(distinct: true).paginate(:per_page => 20, :page => params[:page])
  end

  def create
    tag = Tag.find_or_create_by(:name => tag_params[:name])
    unless @post.nil? or @post.tags.exists?(tag)
      @post.tags << tag
      result = {:tag => render_to_string(:partial => 'tag', :locals =>{:tag => tag, :post => @post})}
    end
    result ||= {:error => "Association between tag_id #{tag.id} and post_id #{params[:post_id]} already exist or post not found"}
    render :json => result
  end

  def update
    if @tag.update_attributes(tag_params)
      flash[:notice] = "Updated successfully"
      redirect_to administration_tags_path
    else
      flash[:error] = @tag.errors.to_a
      render :action => :edit
    end
  end

  def search_tag
    tag = Tag.where("LOWER(name) LIKE (?)", "%#{params[:q].to_s.downcase}%")
    render :text => tag.map(&:name).uniq.join("\n")
  end

  def destroy
    if @tag and @post and @post.tags.delete(@tag)
      render :text => "ok"
    else
      render :text => "Error while deleting association between tag_id #{params[:id]} and post_id #{params[:post_id]}"
    end
  end

  def destroy!
      @tag.destroy
      flash[:notice] = "Tag #{@tag.name} has been successfully deleted"
      redirect_to administration_tags_path
  end

  private

  def tag_params
    params[:tag].permit(:name, :post_id, :q, :search, :page)
  end

  def find_post
    @post = Post.find_by_id(params[:post_id])
  end

  def find_tag
    unless @tag = Tag.find_by(:id => params[:id])
      flash[:error] = "Tag with id #{params[:id]} not found"
      redirect_to administration_tags_path unless request.xhr?
    end
  end

end

app/helpers/administration/main_helper.rb
module Administration::MainHelper
  def has_active_class?(href)
    current_page?(href) ? {:class => "active"} : []
  end
end

app/views/administration/comments/_form.html.haml
.group
  = f.label "Author:"
  = f.text_field :author, :value => @comment.author || current_admin.nick
.group
  = f.label "Content:"
  = f.text_area :content
.group.navform.wat-cf
  = f.submit "Save"
  = link_to "Cancel", administration_post_path(post)

app/views/administration/comments/_search_sidebar.html.haml
.block.notice
  %h3 Search
  .comment_search
    = search_form_for @search, :url => administration_comments_path, :html => {:method => :get} do |f|
      .search_attr
        %p
          = f.label :created_at, "Begin Date "
          = f.date_select :created_at, :default=>5.years.ago
        %p
          = f.label :created_at, "End Date "
          = f.date_select :created_at
      %p
        = f.submit "Search"
        = link_to "Reset",administration_comments_path

app/views/administration/comments/_sidebar.html.haml
.block.notice
  .comment_search
.block
  %h3 Links
  %ul.navigation
    %li
      %a{:href => "#"} Link 1
    %li
      %a{:href => "#"} Link 2

app/views/administration/comments/edit.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "List", administration_comments_path
      %li.active= link_to "Edit", edit_administration_comment_path(@comment)
  .content
    %h2.title
      Edit comment
    .inner
      = form_for @comment, :url => administration_comment_path(@comment) do |f|
        = render :partial => 'form', :locals => {:f => f, :post => @comment.post}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')

app/views/administration/comments/index.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first.active= link_to "List", "#"
  .content
    %h2.title
      All Comments
    .inner
      %table.table
        %tr
          %th.first= sort_link @search, :created_at, "Comments"
          %th.last &nbsp;
        - @comments.each do |comment|
          %tr{:class => cycle("odd", "even")}
            %td= comment.content
            %td.last.show-comments
              %p
                %strong
                  ID:
                = comment.id
              %p
                %strong
                  Post ID:
                = comment.post.id
              %p
                %strong
                  Post Subject:
                = link_to comment.post.subject, administration_post_path(comment.post)
              %p
                %strong
                  Author:
                = comment.author
              %p
                %strong
                  Created at:
                = l(comment.created_at,:format => :long)
              %p
                %strong
                  Updated at:
                = l(comment.updated_at,:format => :long)
              %p
                \#{link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_administration_comment_path(comment)}
                |
                \#{link_to "#{t("web-app-theme.delete", :default => "Delete")}", administration_comment_path(comment), :method => :delete, :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}"}

    = will_paginate @comments
- content_for :sidebar, render(:partial => 'search_sidebar')

app/views/administration/comments/new.html.haml
.block
  .secondary-navigation
    %ul.wat-cf
      %li.first= link_to "List", administration_comments_path
      %li.active= link_to "New", new_administration_post_comment_path(@post)
  .content
    %h2.title
      New comment
    .inner
      = form_for @comment, :url => administration_post_comments_path(@post) do |f|
        = render :partial => 'form', :locals => {:f => f, :post => @post}
      .actions-bar.wat-cf
        .actions
- content_for :sidebar, render(:partial => 'sidebar')