config/routes.rb
RubyBlog::Application.routes.draw do
  devise_for :admins
  root :to => 'users#index'
  scope "/" do
    get "/post/:id" => "users#show", :as => :show_post_comments
    post "/post/:id" => "users#create", :as => :create_comment
  end

  get "/administration" => "administration/comments#index"
  get "/search" => "search#index"

  get "/categories/:name" => "tags#index", :as => :tags

  namespace :administration do
    resources :admins
    resources :posts do
      collection do
        get :preview
      end
      resources :comments, :only => [:new, :create]
    end
    resources :comments, :except => [:new, :create]
    resources :tags
    resources :sitemap, :only => [:index, :create]
  end
  delete "/administration/tags/destroy/:id" => "administration/tags#destroy!", :as => :administration_destroy_tag
  get "/administration/search_tag" => "administration/tags#search_tag", :as => :administration_search_tag
  get "/administration/admins/disable/:id" => "administration/admins#disable", :as => :disable_administration_admin
end

app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Ruby Blog admin panel
    = stylesheet_link_tag "administration/admins"
    :javascript
      var CKEDITOR_BASEPATH = '/assets/ckeditor/';
    = javascript_include_tag "administration/admins"
    = csrf_meta_tags
  %body
    #container
      #header
        %h1
          %a{:href => "/"} Ruby Blog admin panel
        #user-navigation
          %ul.wat-cf
            %li
              = link_to "Profile", administration_admin_path(current_admin)
            %li
              =link_to "Logout", destroy_admin_session_path, :method => :delete
        #main-navigation
          %ul.wat-cf
            %li{has_active_class?(administration_admins_path)}= link_to "Admins", administration_admins_path
            %li{has_active_class?(administration_posts_path)}= link_to "Posts",administration_posts_path
            %li{has_active_class?(administration_comments_path)}= link_to "Comments", administration_comments_path
            %li{has_active_class?(administration_tags_path)}= link_to "Tags", administration_tags_path
            %li{has_active_class?(administration_sitemap_index_path)}= link_to "SiteMap", administration_sitemap_index_path
      #wrapper.wat-cf
        .flash
          - flash.each do |type, message|
            %div{:class => "message #{type}"}
              %p= message
        #main
          = yield
          #footer
            .block
              %p{:style => "text-align: center;"}
                Copyright &copy; #{Time.now.year} Ruby Blog by #{link_to "Max Dolgih", "https://github.com/hiddenfile", :rel => "nofollow"} & #{link_to "Ivan Dzyzenko", "https://github.com/intale", :rel => "nofollow"}
        #sidebar
          = yield :sidebar

app/views/layouts/application.html.haml
!!!
%html{:dir => "ltr", :xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title= meta_content[:title]
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
    %meta{:content => meta_content[:keywords], :name => "keywords"}
    %meta{:content => meta_content[:description], :name => "description"}/
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = javascript_include_tag "https://apis.google.com/js/plusone.js"
    = csrf_meta_tags
    :javascript
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-26174162-1']);
      _gaq.push(['_setDomainName', 'is-valid.org']);
      _gaq.push(['_trackPageview']);
      (function() {
       var ga = document.createElement('script');
       ga.type = 'text/javascript';
       ga.async = true;
       ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
       var s = document.getElementsByTagName('script')[0];
       s.parentNode.insertBefore(ga, s);
      })();

  %body
    / main styles
    .main.index
      .main1
        / H E A D E R  start
        .header
          %a.logo{:href => root_path}

          / h-menu start
          .h-menu
            #menu-elements
              %ul
                %li= link_to "Home", root_path
                %li= link_to "News", tags_path("News")
                %li
                  %a{:href => "javascript: void(0);"} FAQ
                %li= link_to "About Us", tags_path("About Us")
            #search-form
              = form_tag search_path, :method => "GET" do
                = text_field_tag :request
                = link_to "Search", "javascript: void(0);", :id => "submit-search"
                = hidden_field_tag :category, "in posts"

            .clear
          / h-menu end
        / H E A D E R  end
        / C O N T E N T  start

        .content
          = yield
          .right
            %h3 Categories
            .r-menu
              %ul
              - @tags.each do |tag|
                %li= link_to tag.name, tags_path(tag.name)
          / R I G H T
          .clear
        / C O N T E N T  end
    / /main styles
    / F O O T E R  start
    .footer
      Copyright &copy; #{Time.now.year} Ruby Blog by #{link_to "Max Dolgih", "https://github.com/hiddenfile", :rel => "nofollow"} & #{link_to "Ivan Dzyzenko", "https://github.com/intale", :rel => "nofollow"}
    / F O O T E R  end